title: Gwendal
owner: Gwendal
email:
description: Gwendal's WebSite
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gpensta.github.io"
language: en
twitter_username:
github_username:
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile 
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
